version: "3.5"
services:
  sequencer:
    build:
      args:
        NETWORK: "alpha-testnet"
    environment:
      ETHEREUM_HOSTS: http://geth.sepolia-geth.dappnode:8545
      L1_CONSENSUS_HOST_URLS: http://prysm-sepolia.dappnode:3500
    ports:
      - 40400:40400/tcp
      - 40400:40400/udp
